# Generated by Django 5.2.8 on 2025-11-27 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa zaparzacza"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
            ],
            options={
                "verbose_name": "Zaparzacz",
                "verbose_name_plural": "Zaparzacze",
            },
        ),
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa kawy")),
                (
                    "processing",
                    models.CharField(max_length=100, verbose_name="Obróbka"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Kraj")),
                (
                    "variety",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Odmiana"
                    ),
                ),
                (
                    "roast_level",
                    models.CharField(max_length=100, verbose_name="Stopień palenia"),
                ),
            ],
            options={
                "verbose_name": "Kawa",
                "verbose_name_plural": "Kawy",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brewers",
                    models.ManyToManyField(
                        blank=True, to="brewing.brewer", verbose_name="Moje zaparzacze"
                    ),
                ),
                (
                    "coffees",
                    models.ManyToManyField(
                        blank=True, to="brewing.coffee", verbose_name="Moje kawy"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coffee_amount", models.IntegerField(verbose_name="Ilość kawy (g)")),
                (
                    "grind_size",
                    models.CharField(max_length=100, verbose_name="Stopień zmielenia"),
                ),
                (
                    "brewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brewing.brewer",
                        verbose_name="Zaparzacz",
                    ),
                ),
                (
                    "coffee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brewing.coffee",
                        verbose_name="Kawa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przepis",
                "verbose_name_plural": "Przepisy",
            },
        ),
        migrations.CreateModel(
            name="RecipePhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200, verbose_name="Czynność")),
                (
                    "time",
                    models.CharField(max_length=100, verbose_name="Czas (np. 30s)"),
                ),
                (
                    "water_amount",
                    models.CharField(max_length=100, verbose_name="Ilość wody (g)"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="brewing.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faza parzenia",
                "verbose_name_plural": "Fazy parzenia",
                "ordering": ["order"],
            },
        ),
    ]
